apps/homework/urls.py
from django.urls import path
from . import views


app_name = 'homework'

urlpatterns = [
    path('define/<int:klass_pk>/', views.DefinitionFormView.as_view(), name='define_homework'),
    path('edit_definition/<int:klass_pk>/<int:definition_pk>', views.DefinitionEditFormView.as_view(), name='edit_homework_def'),
    path('grade/<int:klass_pk>/submission/<int:submission_pk>/', views.GradeFormView.as_view(), name='grade_homework'),
    path('grade/<int:klass_pk>/submission/<int:submission_pk>/edit/<int:grade_pk>', views.GradeEditFormView.as_view(), name='edit_grade'),
    path('overview/<int:klass_pk>/', views.HomeworkOverView.as_view(), name='overview'),
    path('submissions/<int:definition_pk>/', views.SubmissionListView.as_view(), name='submission_list'),
    path('submission/<int:submission_pk>/', views.SubmissionDetailView.as_view(), name='submission_detail'),
    path('submit/<int:klass_pk>/<int:definition_pk>/<int:use_github>/', views.SubmissionFormView.as_view(), name='submit_homework'),
    path('edit_submission/<int:klass_pk>/<int:definition_pk>/<int:submission_pk>/<int:use_github>/', views.SubmissionEditFormView.as_view(), name='edit_submission'),
    path('download_grades_csv/<int:klass_pk>', views.get_klass_grades_as_csv, name='get_grades_csv'),
]

apps/klasses/urls.py
from django.urls import path

from apps.klasses import views

app_name = 'klasses'

urlpatterns = [
    path('create/', views.CreationView.as_view(), name='create_klass'),
    path('edit/<int:klass_pk>', views.EditView.as_view(), name='edit_klass'),
    path('wizard/<int:klass_pk>', views.OverView.as_view(), name='klass_details'),
    path('wizard/<int:klass_pk>/enroll', views.EnrollmentView.as_view(), name='klass_enrollment'),
    path('wizard/<int:klass_pk>/define_homework', views.DefineHomeworkView.as_view(), name='klass_homework'),
    path('wizard/<int:klass_pk>/grade_homework', views.GradeHomeworkView.as_view(), name='klass_grading'),
    path('wizard/<int:klass_pk>/answers/<int:definition_pk>/', views.HomeworkAnswersView.as_view(), name='homework_answers'),
    path('wizard/<int:klass_pk>/activate', views.ActivateView.as_view(), name='klass_activate'),
    path('download_student_csv/<int:klass_pk>', views.get_klass_students_as_csv, name='klass_get_student_csv'),
]

apps/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('reset_user_password/<int:user_pk>/', views.ResetUserPasswordView.as_view(), name='reset_user_password'),
    path('reset_password_by_email/<uuid:reset_key>/', views.ResetUserPasswordByEmailKeyView.as_view(), name='reset_password_by_email'),
    path('remove_user_password_reset_requests/<int:user_pk>/', views.DeletePasswordResetRequestsView.as_view(), name='remove_user_password_reset_requests'),
    path('request_password_reset/<int:sent_message>/', views.RequestResetView.as_view(), name='request_password_reset'),
    path('password_reset_requests/', views.PasswordRequestsOverView.as_view(), name='password_reset_requests'),
    path('instructor_signup/', views.InstructorProfileCreationView.as_view(), name='instructor_signup'),
    path('instructor_overview/', views.InstructorOverView.as_view(), name='instructor_overview'),
    path('student_overview/', views.StudentOverView.as_view(), name='student_overview'),
    path('my_profile/', views.MyProfileView.as_view(), name='my_profile')
]

chagrade/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView


from apps.klasses.models import Klass
from apps.homework.models import Submission
from apps.profiles.models import StudentMembership, ChaUser, Instructor

urlpatterns = [
    # Our includes
    path('admin/', admin.site.urls),
    path('profiles/', include('apps.profiles.urls', namespace='profiles')),
    path('klasses/', include('apps.klasses.urls', namespace='klasses')),
    path('metrics/', include('apps.metrics.urls', namespace='metrics')),
    path('homework/', include('apps.homework.urls', namespace='homework')),
    path('groups/', include('apps.groups.urls', namespace='groups')),
    path('social/', include('social_django.urls', namespace='social')),
    path('api/<str:version>/', include('apps.api.urls')),
]


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        stats_data = {
            "users": ChaUser.objects.count(),
            "students": StudentMembership.objects.count(),
            "instructors": Instructor.objects.count(),
            "submissions": Submission.objects.count(),
            "klasses": Klass.objects.count(),
        }
        context.update(stats_data)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Home-Page'
        return context


urlpatterns.append(path('', IndexView.as_view(), name='index'))


# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/homework/forms.py
from django import forms
from django.forms import DateTimeInput, SelectDateWidget

from apps.homework.models import Definition, Submission, Grade, Criteria


class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = [
            'github_url'
        ]


class DefinitionForm(forms.ModelForm):
    class Meta:
        model = Definition
        fields = [
            'due_date',
            'name',
            'description',
            'challenge_url',
            'starting_kit_github_url',
            'baseline_score',
            'target_score',
            'ask_method_name',
            'ask_method_description',
            'ask_project_url',
            'ask_publication_url',
            'team_based',
        ]
        widgets = {
            'due_date': SelectDateWidget()
        }


class DefinitionEditForm(forms.ModelForm):
    criterias = forms.ModelMultipleChoiceField(queryset=Criteria.objects.all())

    class Meta:
        model = Definition
        fields = [
            'due_date',
            'name',
            'description',
            'challenge_url',
            'starting_kit_github_url',
            'baseline_score',
            'target_score',
            'ask_method_name',
            'ask_method_description',
            'ask_project_url',
            'ask_publication_url',
            'team_based',
            # 'criterias'
        ]
        widgets = {
            'due_date': SelectDateWidget()
        }


class GradeForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = [
            # 'score',
            'teacher_comments',
            'instructor_notes',
        ]

apps/api/views/homework.py
import logging

from django.contrib.auth import get_user_model
from django.db.models import Prefetch
from rest_framework import status
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from apps.api.permissions import SubmissionPermissionCheck, GradePermissionCheck, DefinitionPermissionCheck, \
    QuestionPermissionCheck, CriteriaPermissionCheck, CustomChallengeURLPermissionCheck
from apps.api.serializers.homework import DefinitionSerializer, QuestionSerializer, CriteriaSerializer, \
    SubmissionSerializer, GradeSerializer, TeamCustomChallengeURLSerializer
from apps.homework.models import Definition, Question, Criteria, Submission, Grade, TeamCustomChallengeURL
from apps.homework.tasks import post_submission, SubmissionPostException

User = get_user_model()

logger = logging.getLogger(__name__)


class GradeViewSet(ModelViewSet):
    queryset = Grade.objects.all()
    serializer_class = GradeSerializer
    permission_classes = (GradePermissionCheck,)

    def perform_create(self, serializer):
        new_obj = serializer.save()
        new_obj.calculate_grade()

    def perform_update(self, serializer):
        new_obj = serializer.save()
        new_obj.calculate_grade()


class SubmissionViewSet(ModelViewSet):
    queryset = Submission.objects.all()
    serializer_class = SubmissionSerializer
    permission_classes = (SubmissionPermissionCheck,)

    def create(self, request, *args, **kwargs):
        """Overwritten so we can return responses or default from post_submission"""
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        response = self.perform_create(serializer)
        if response:
            return response
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def perform_create(self, serializer):
        serializer.is_valid(raise_exception=True)
        new_sub = serializer.save()

        # Move grade and other answers from most recent submission to this new submission
        pre_existing_submission = new_sub.creator.submitted_homeworks.order_by('created').filter(definition=new_sub.definition).exclude(pk=new_sub.pk).last()
        if pre_existing_submission is not None:
            pre_existing_grade = pre_existing_submission.grades.last()
            if pre_existing_grade is not None:
                pre_existing_grade.submission = new_sub
                pre_existing_grade.needs_review = True
                pre_existing_grade.save()

        if new_sub.pk and not new_sub.submitted_to_challenge:
            file_to_submit = self.request.data.get('file')
            if not new_sub.definition.questions_only and ( new_sub.github_url or file_to_submit ):
                if file_to_submit:
                    # If we were given a file even though this definition only accepts github submissions, return an error
                    if new_sub.definition.force_github:
                        logger.warning(f"Submission {new_sub.pk} is a direct upload and it should be a github submission!")
                        return Response(
                            "This homework only takes github submissions!",
                            status=status.HTTP_400_BAD_REQUEST
                        )
                    logger.info(f"Submission {new_sub.pk} is a direct upload!")
                    new_sub.is_direct_upload = True
                    new_sub.save()
                else:
                    logger.info(f"Submission {new_sub.pk} is a github submission!")
                try:
                    post_submission(new_sub.pk, file_to_submit)
                except SubmissionPostException as e:
                    if e.sub_type == 'connection':
                        return Response(
                            "Could not communicate with Codalab instance!",
                            status=status.HTTP_504_GATEWAY_TIMEOUT
                        )
                    else:
                        return Response(
                            "Could not determine data to send to Codalab. Check you supplied a proper github_url, or a "
                            "file for direct upload.",
                            status=status.HTTP_400_BAD_REQUEST
                        )


class DefinitionViewSet(ModelViewSet):
    queryset = Definition.objects.all()
    queryset = Definition.objects.all().prefetch_related(Prefetch(
        'custom_questions',
        queryset=Question.objects.all()))
    serializer_class = DefinitionSerializer
    permission_classes = (DefinitionPermissionCheck,)


class QuestionViewSet(ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer
    permission_classes = (QuestionPermissionCheck,)


class CriteriaViewSet(ModelViewSet):
    queryset = Criteria.objects.all()
    serializer_class = CriteriaSerializer
    permission_classes = (CriteriaPermissionCheck, )


class CustomChallengeURLViewSet(ModelViewSet):
    queryset = TeamCustomChallengeURL.objects.all()
    serializer_class = TeamCustomChallengeURLSerializer
    permission_classes = (CustomChallengeURLPermissionCheck, )

apps/homework/templates/homework/forms/define_homework.html
{% extends 'klasses/wizard/wizard_base.html' %}

{% block wizard_title %}
    <h2 class="ui massive header" style="font-size: 56px;">Define Homework</h2>
{% endblock %}


{% block wizard_content %}
    <div class="ui centered grid">
        <div class="row">
            <div class="ui fourteen wide column message">
                <define-homework></define-homework>
            </div>
        </div>
    </div>

{% endblock %}

apps/homework/templates/homework/forms/edit_homework_def.html
{% extends 'klasses/wizard/wizard_base.html' %}

{% block wizard_title %}
    <h2 class="ui massive header" style="font-size: 56px;">Define Homework</h2>
{% endblock %}


{% block wizard_content %}
    <div class="ui centered grid">
        <div class="row">
            <div class="ui fourteen wide column message">
                <form class="ui form" method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    <div class="fields">

                        {% for field in form %}
                            {% if forloop.counter0|divisibleby:4 %}
                                </div>
                                <div class="fields">
                            {% endif %}
                            <div class="four wide field">
                                {{ field.errors }}
                                <span>
                                    {{ field.label_tag }}
                                    {{ field }}
                                </span>
                            </div>
                        {% endfor %}
                    </div>
                    <span>
                        <input class="ui green button" type="submit" value="Submit">
                        <a href="{% url "klasses:klass_homework" klass_pk=klass.pk %}" class="ui red button">Cancel</a>
                    </span>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

apps/homework/templates/homework/forms/grade_homework.html
{% extends 'klasses/wizard/wizard_base.html' %}
{% load homework_tags %}

{% block wizard_title %}
    <h2 class="ui massive header" style="font-size: 56px;">Grade Homework</h2>
{% endblock %}


{% block wizard_content %}
    <div class="ui centered grid">
        <div class="row">
            <div class="ui fourteen wide column message">
                <h4 class="ui header">Submission Info: {{ submission.definition }}</h4>
                <div class="ui relaxed celled list">
                    <div class="item">First Name: {{ submission.creator.user.first_name }}</div>
                    <div class="item">Last Name: {{ submission.creator.user.last_name }}</div>
                    <div class="item">Username: {{ submission.creator.user.username }}</div>
                    <div class="item">Email: {{ submission.creator.user.email }}</div>
                    <div class="item">Team Leader: {{ submission.team.leader }}</div>
                    {% if submission.tracked_submissions.all %}
                        {% for tracker in submission.tracked_submissions.all %}
                            <div class="item">Submission Info: ID - {{ tracker.remote_id }}; Score - {{ tracker.score }}; Status - {{ tracker.status }}; Phase - {{ tracker.remote_phase }}</div>
                        {% endfor %}
                    {% else %}
                        <div class="item">No Submission</div>
                    {% endif %}
                    <div class="item">Submission Date: {{ submission.created }}</div>
                </div>

                {% if not definition.questions_only %}
                    <h4 class="ui header">Challenge Rules</h4>
                    <div class="ui relaxed celled list">
                        <a href="{{ definition.challenge_url }}" class="item" target="_blank" rel="noopener noreferrer">Link to challenge competition</a>
                        {% if submission.github_url %}
                            <a
                               href="{{ submission.nb_viewer_format_submission_url }}"
                               class="item"
                               target="_blank"
                               rel="noopener noreferrer"
                            >
                            {% if definition.jupyter_notebook_enabled %}
                                Link to submission</a>
                            {% else %}
                                Link to Github repo of submission</a>
                            {% endif %}
                        {% endif %}
                        <a class="ui mini blue button" href="{% url "homework:submission_detail" submission_pk=submission.pk %}">Submission Details</a>
                    </div>

                    {% if definition.jupyter_notebook_enabled %}
                        <h4 class="ui header">Jupyter Notebook</h4>
                        <div class="ui relaxed celled list">
                            <div>Auto-Grade Score: {{ submission.jupyter_score }} / {{ definition.jupyter_notebook_highest }}</div>
                            {% if submission_jupyter_warnings %}
                                <div>Auto-Grade Warnings:</div>
                                <ul>
                                {% for warning in submission_jupyter_warnings %}
                                    <li>{{ warning }}</li>
                                {% endfor %}
                                </ul>
                            {% endif %}

                            {% if submission_jupyter_errors %}
                                <div>Auto-Grade Errors:</div>
                                <ul>
                                {% for error in submission_jupyter_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    {% endif %}

                {% endif %}

                <h4>Questions</h4>
                <div class="ui relaxed celled list">
                    <ol>
                        {% if definition.ask_method_name %}
                            <li><b>Method Name:</b> {{ submission.method_name }}</li>{% endif %}
                        {% if definition.ask_method_description %}
                            <li><b>Method Description:</b> {{ submission.method_description }}</li>{% endif %}
                        {% if definition.ask_project_url %}
                            <li><b>Project URL:</b>
                                <a href="{{ submission.project_url }}"
                                   target="_blank" rel="noopener noreferrer"
                                >{{ submission.project_url }}</a></li>{% endif %}
                        {% if definition.ask_publication_url %}
                            <li><b>Publication URL:</b>
                                <a href="{{ submission.publication_url }}"
                                   target="_blank" rel="noopener noreferrer"
                                >{{ submission.publication_url }}</a></li>{% endif %}
                    </ol>
                    {% if not definition.has_standard_questions %}
                        <p>No standard questions defined for this homework.</p>
                    {% endif %}
                </div>
                <grade-homework></grade-homework>
            </div>
        </div>
    </div>
{% endblock %}

apps/homework/templates/homework/forms/overview.html
{% extends 'base.html' %}
{% load static %}
{% load homework_tags %}

{% block title %}Welcome{% endblock %}

{% block extra_head %}
    <style>
        .condensed {
            margin: 0.5vh 0 0 0 !important;
            padding: 0.5vh 0 0 0 !important;
        }

        .no-padding {
            padding: 1vh 0 0 0 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="ui centered grid">
        <div class="row">
        <a class="ui blue button" href="{% url 'profiles:student_overview' %}">Back to Student Overview</a>
            <div class="fourteen wide column">
                <div class="ui centered grid segment">
                    <div class="row">
                        <div class="two wide column">
                            <img style="height: 100px; width: auto;" src="{% static "images/dark-triangles.png" %}">
                        </div>
                        <div class="fourteen wide column">
                            <div class="ui grid">
                                <div class="row no-padding">
                                    <div class="twelve wide column">
                                        <h1 class="ui header">{{klass.title}}</h1>
                                        {% if klass.group %}
                                            <h4 class="ui header condensed">From Group: {{ klass.group.name }}</h4>
                                        {% endif %}
                                        <h4 class="ui header condensed">Organized by: {{ klass.instructor.user.username }}</h4>
                                    </div>
                                    <div class="four wide column">
                                        <h5 class="ui header condensed">Created: {{klass.created.date}}</h5>
                                        <h5 class="ui header condensed">Modified: {{klass.modified.date}}</h5>
                                    </div>
                                </div>
                                <div class="row no-padding">
                                    <div class="sixteen wide column">
                                        Description: {{ klass.description }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ui header">Assignments for Class {{ klass.title }}</div>
                {% for definition in klass.homework_definitions.all %}
                    {% with definition|get_last_submission:user.pk as submission %}
                        {% with submission|get_last_grade as grade %}
                            <div class="ui message">
                                <div class="content">
                                    <div class="header">
                                        {{ definition.name }}
                                    </div>
                                    <hr>
                                    <h4>Due Date: {{ definition.due_date }}</h4>
                                    <p>{{ definition.description }}</p>
                                    {% if definition.team_based %}
                                        <h4>Graded as teamwork</h4>
                                    {% endif %}
                                    <div class="ui grid">
                                        <div class="row">
                                            <div class="eight wide column">
                                                <h4 class="ui header">Submission:</h4>
                                                <ul class="ui relaxed celled list">
                                                    {% if definition.ask_method_name %}<div class="item">Method Name:
                                                        {{ submission.method_name }}</div>{% endif %}
                                                    {% if definition.ask_method_description %}<div class="item">Method Description:
                                                        {{ submission.method_description }}</div>{% endif %}
                                                    {% if definition.ask_project_url %}<div class="item">Project URL:
                                                        {{ submission.project_url }}</div>{% endif %}
                                                    {% if definition.ask_publication_url %}<div class="item">Publication URL:
                                                        {{ submission.publication_url }}</div>{% endif %}
                                                </ul>
                                            </div>
                                            <div class="eight wide column">
                                                {% if submission %}
                                                    <a href="{% url "homework:submit_homework" klass_pk=klass.pk definition_pk=definition.pk %}"
                                                       class="ui yellow button">Edit/Re-Submit Homework</a>
                                                    <a href="" class="ui button">View Challenge Submission</a>
                                                {% else %}
{#                                                    No Submission!#}
                                                    <a href="{% url "homework:submit_homework" klass_pk=klass.pk definition_pk=definition.pk %}"
                                                       class="ui blue button">Submit Homework</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="eight wide column">Grade:</div>
                                            <div class="eight wide column">{{ grade.overall_grade }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endwith %}
                    {% endwith %}
                {% endfor %}
{#                <form class="ui form" method="post">#}
{#                    {% csrf_token %}#}
{##}
{#                    {{ form.non_field_errors }}#}
{##}
{#                    {% for field in form %}#}
{#                        <div class="field">#}
{#                            {{ field.errors }}#}
{#                            <span>#}
{#                                {{ field.label_tag }}#}
{#                                {{ field }}#}
{#                            </span>#}
{#                        </div>#}
{#                    {% endfor %}#}
{##}
{#                    <input type="submit" value="Submit">#}
{#                </form>#}
            </div>
        </div>
    </div>
{% endblock %}

apps/homework/templates/homework/forms/submit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="ui centered grid">
        <div class="row">
        <a class="ui blue button" href="{% url 'profiles:student_overview' %}">Back to Student Overview</a>
            <div class="fourteen wide column">
                {% include "klasses/klass_header.html" %}

                <submit-homework github="{{ github }}" pk="{{ request.user.id }}"></submit-homework>
            </div>
        </div>
    </div>
{% endblock %}