apps/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('reset_user_password/<int:user_pk>/', views.ResetUserPasswordView.as_view(), name='reset_user_password'),
    path('reset_password_by_email/<uuid:reset_key>/', views.ResetUserPasswordByEmailKeyView.as_view(), name='reset_password_by_email'),
    path('remove_user_password_reset_requests/<int:user_pk>/', views.DeletePasswordResetRequestsView.as_view(), name='remove_user_password_reset_requests'),
    path('request_password_reset/<int:sent_message>/', views.RequestResetView.as_view(), name='request_password_reset'),
    path('password_reset_requests/', views.PasswordRequestsOverView.as_view(), name='password_reset_requests'),
    path('instructor_signup/', views.InstructorProfileCreationView.as_view(), name='instructor_signup'),
    path('instructor_overview/', views.InstructorOverView.as_view(), name='instructor_overview'),
    path('student_overview/', views.StudentOverView.as_view(), name='student_overview'),
    path('my_profile/', views.MyProfileView.as_view(), name='my_profile')
]

chagrade/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView


from apps.klasses.models import Klass
from apps.homework.models import Submission
from apps.profiles.models import StudentMembership, ChaUser, Instructor

urlpatterns = [
    # Our includes
    path('admin/', admin.site.urls),
    path('profiles/', include('apps.profiles.urls', namespace='profiles')),
    path('klasses/', include('apps.klasses.urls', namespace='klasses')),
    path('metrics/', include('apps.metrics.urls', namespace='metrics')),
    path('homework/', include('apps.homework.urls', namespace='homework')),
    path('groups/', include('apps.groups.urls', namespace='groups')),
    path('social/', include('social_django.urls', namespace='social')),
    path('api/<str:version>/', include('apps.api.urls')),
]


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        stats_data = {
            "users": ChaUser.objects.count(),
            "students": StudentMembership.objects.count(),
            "instructors": Instructor.objects.count(),
            "submissions": Submission.objects.count(),
            "klasses": Klass.objects.count(),
        }
        context.update(stats_data)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Home-Page'
        return context


urlpatterns.append(path('', IndexView.as_view(), name='index'))


# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/api/views/profiles.py
import csv

from django.contrib.auth import get_user_model
from rest_framework.decorators import api_view
from rest_framework.generics import GenericAPIView, RetrieveAPIView
from rest_framework import permissions, status
from rest_framework.mixins import RetrieveModelMixin, ListModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet, ModelViewSet
from rest_framework.exceptions import ValidationError, ErrorDetail

from apps.api.permissions import StudentPermissionCheck, UserPermissionCheck
from apps.api.serializers.profiles import ChaUserSerializer, TestStudentSerializer

from apps.api import serializers

from apps.profiles.models import ChaUser, StudentMembership

User = get_user_model()


class GetMyProfile(RetrieveAPIView, GenericAPIView):
    # queryset = User.objects.all()
    serializer_class = ChaUserSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_object(self):
        return self.request.user


class ProfileViewSet(RetrieveModelMixin, ListModelMixin, GenericViewSet):
    queryset = ChaUser.objects.all()
    serializer_class = serializers.profiles.ChaUserSerializer
    permission_classes = (UserPermissionCheck,)


class StudentViewSet(ModelViewSet):
    queryset = StudentMembership.objects.all()
    serializer_class = serializers.profiles.DetailedStudentSerializer
    permission_classes = (StudentPermissionCheck,)


class TestStudentViewSet(ModelViewSet):
    queryset = StudentMembership.objects.all()
    serializer_class = serializers.profiles.TestStudentSerializer


def make_ordinal(n):
    """Convert an integer into its ordinal representation:

       make_ordinal(0)   => '0th'
       make_ordinal(3)   => '3rd'
       make_ordinal(122) => '122nd'
       make_ordinal(213) => '213th'
    """
    n = int(n)
    suffix = ['th', 'st', 'nd', 'rd', 'th'][min(n % 10, 4)]
    if 11 <= (n % 100) <= 13:
        suffix = 'th'
    return f'{n}{suffix}'


@api_view(['POST'])
def create_students_from_csv(request, version):
    with open(request.FILES['file'].temporary_file_path()) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        line_count = 0
        for row in csv_reader:
            if len(row) >= 6:
                if line_count == 0 and 'first name' in row[0].lower() and 'student id' in row[3].lower() and 'student email' in row[4].lower():
                    continue
                data = {
                    'user': {
                        'first_name': row[0],
                        'last_name': row[1],
                        'username': row[2],
                        'email': row[4],
                    },
                    'student_id': row[3],
                    'klass': request.data.get('klass'),
                }

                contains_valid_team_name = any(character.isalpha() for character in row[5])

                if contains_valid_team_name:
                    data['team'] = {
                        'name': row[5],
                        'klass': request.data.get('klass')
                    }
                new_student_serializer = TestStudentSerializer(data=data)
                try:
                    new_student_serializer.is_valid(raise_exception=True)
                except ValidationError:
                    if new_student_serializer.errors:
                        error_dict = dict(new_student_serializer.errors).get('user')
                        field_errors_string = ''
                        for key in error_dict:
                            for error_string in error_dict[key]:
                                field_errors_string += error_string + ' \n'
                        raise ValidationError(f'From top of CSV, {make_ordinal(line_count + 1)} student with email: {str(row[4])}: {field_errors_string}')

                new_student = new_student_serializer.save()
                # If there's something in the student leader column
                if len(row) == 7 and contains_valid_team_name and row[6].lower() in ['t', 'true']:
                    new_student.team.leader = new_student
                    new_student.team.save()
            else:
                print("Row too short to read.")
            line_count += 1
        print('Processed {} lines.'.format(line_count))
    return Response({'response': 'success'})

apps/profiles/views.py
# Create your views here.
import logging

from django.conf import settings
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import FormView, TemplateView

from django.contrib.auth.forms import PasswordChangeForm

from apps.profiles.forms import InstructorProfileForm, ChagradeCreationForm, ChagradeUserLoginForm
from apps.profiles.models import ChaUser, PasswordResetRequest
from apps.profiles.utils import send_chagrade_mail


logger = logging.getLogger(__name__)


def logout_view(request):
    #  TODO: Make confirmation that you want to logout?
    logout(request)
    # Redirect to a success page.
    return redirect(reverse('index'))


class ChangePasswordView(LoginRequiredMixin, FormView):
    template_name = 'profiles/change_password.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('index')

    def get_form_kwargs(self, **kwargs):
        data = super().get_form_kwargs(**kwargs)
        data['user'] = self.request.user
        return data

    def form_valid(self, form):
        self.request.user.set_password(form.cleaned_data['new_password1'])
        self.request.user.save()
        user = authenticate(request=self.request, email=self.request.user.email, password=form.cleaned_data['new_password1'])
        if not user:
            form.add_error(field=None,
                           error="Incorrect email/password combination. Please double check your credentials.")
            return super().form_invalid(form)
        login(self.request, user, backend="apps.profiles.auth_backends.EmailBackend")
        return super().form_valid(form)


class RequestResetView(TemplateView):
    template_name = 'profiles/request_password_reset.html'

    def post(self, request, *args, **kwargs):
        if not request.method == 'POST':
            return Http404("Wrong method")
        if self.request.POST.get('email'):
            try:
                user = ChaUser.objects.get(email=self.request.POST.get('email'))
                if not PasswordResetRequest.objects.filter(user=user):
                    reset_request = PasswordResetRequest.objects.create(user=user)
                    reset_request_link = reset_request.reset_link
                    html_message = f'Someone has requested you reset your password at {settings.SITE_DOMAIN}.\n' \
                                   f'To reset your password please follow the link below:<br>' \
                                   f'<a href="{reset_request_link}">{reset_request_link}</a><br>' \
                                   f"If you choose to change your password, it will be <span style='font-weight: bold;'>{user.email.split('@')[0]}</span>."
                    message = f'Someone has requested you reset your password at {settings.SITE_DOMAIN}.\n' \
                              f'To reset your password please follow the link below:<br>' \
                              f'<a href="{reset_request_link}">{reset_request_link}</a><br>' \
                              f"If you choose to change your password, it will be <span style='font-weight: bold;'>{user.email.split('@')[0]}</span>."
                    subject = 'Chagrade: Password Reset Request'
                    send_chagrade_mail(users=[user], subject=subject, message=message, html_message=html_message)
                    logger.info("Sent password reset request link to email: %s", user.email)
                else:
                    logger.info("Password reset request already exists for %s", user.email)
            except ChaUser.DoesNotExist:
                logger.info("Could not create password reset request for non-existent user from email %s", self.request.POST.get('email'))
        return HttpResponseRedirect(reverse('profiles:request_password_reset', kwargs={'sent_message': 1}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Password-Reset'
        return context


class ResetUserPasswordByEmailKeyView(TemplateView):
    template_name = 'profiles/email_password_reset.html'

    def get(self, request, *args, **kwargs):
        try:
            reset_request = PasswordResetRequest.objects.get(key=self.kwargs.get('reset_key'))
            user = reset_request.user
            user.set_password(user.email.split('@')[0])
            user.save()
            PasswordResetRequest.objects.filter(user=user).delete()
            context = self.get_context_data(**kwargs)
            return self.render_to_response(context)

        except PasswordResetRequest.DoesNotExist:
            raise Http404("We're sorry, but there's no existing password reset request.")


class ResetUserPasswordView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_staff or not self.request.user.is_superuser:
            return Http404("Not allowed")
        user = ChaUser.objects.get(pk=self.kwargs.get('user_pk'))
        user.set_password(user.email.split('@')[0])
        user.save()
        # Clear any password requests for user
        PasswordResetRequest.objects.filter(user=user).delete()
        return HttpResponseRedirect(reverse('index'))


class DeletePasswordResetRequestsView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_staff or not self.request.user.is_superuser:
            return Http404("Not allowed")
        user = ChaUser.objects.get(pk=self.kwargs.get('user_pk'))
        PasswordResetRequest.objects.filter(user=user).delete()
        return HttpResponseRedirect(reverse('index'))


class LoginView(FormView):
    template_name = 'profiles/login.html'
    form_class = ChagradeUserLoginForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        user = authenticate(request=self.request, email=form.cleaned_data['email'], password=form.cleaned_data['password'])
        if not user:
            form.add_error(field=None,
                           error="Incorrect email/password combination. Please double check your credentials.")
            return super().form_invalid(form)
        login(self.request, user, backend="apps.profiles.auth_backends.EmailBackend")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Login'
        return context


class InstructorProfileCreationView(LoginRequiredMixin, FormView):
    template_name = 'profiles/instructor_signup.html'
    form_class = InstructorProfileForm
    success_url = reverse_lazy('profiles:instructor_overview')

    def get_form_kwargs(self, **kwargs):
        data = super().get_form_kwargs(**kwargs)
        return data

    def form_valid(self, form):
        if not self.request.user.instructor:
            self.request.user.instructor = form.save()
            self.request.user.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Create-Instructor'
        return context


class InstructorOverView(LoginRequiredMixin, TemplateView):
    template_name = 'instructor/overview.html'

    def dispatch(self, request, *args, **kwargs):
        # If the user doesn't have an instructor object, re-direct them to fill out the form first
        if request.user.is_authenticated and not self.request.user.instructor:
            return HttpResponseRedirect(reverse('profiles:instructor_signup'))
        else:
            return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Instructor-Class-List'
        return context


class StudentOverView(LoginRequiredMixin, TemplateView):
    template_name = 'student/overview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Your-Classes'
        return context


class MyProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profiles/my_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/My-Profile'
        return context


class SignUpView(FormView):
    template_name = 'profiles/sign_up.html'
    form_class = ChagradeCreationForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Sign-Up'
        return context


class PasswordRequestsOverView(LoginRequiredMixin, TemplateView):
    template_name = 'profiles/password_reset_overview.html'

apps/profiles/templates/profiles/change_password.html
{% extends 'base.html' %}

{% block title %}Change Your Password{% endblock %}

{% block content %}
    <div class="ui vertical masthead center aligned segment">

        <div class="ui center aligned grid">
            <div class="ui six wide column message">

                <form class="ui form" method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    <div class="field">
                        {{ form.old_password.errors }}
                        {{ form.old_password.label_tag }}
                        {{ form.old_password }}
                    </div>

                    <div class="field">
                        {{ form.new_password1.errors }}
                        {{ form.new_password1.label_tag }}
                        {{ form.new_password1 }}
                    </div>

                    <div class="field">
                        {{ form.new_password2.errors }}
                        {{ form.new_password2.label_tag }}
                        {{ form.new_password2 }}
                    </div>


                    <input type="submit" value="Change Password">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

apps/profiles/templates/profiles/email_password_reset.html
{% extends 'base.html' %}

{% block wizard_title %}
    <h2 class="ui massive header" style="font-size: 56px;">Password Reset Success</h2>
{% endblock %}

{% block content %}
    <div class="ui center aligned grid">
        <div class="six wide column">
            <div class="ui center aligned segment">
                <h1 class="ui header">Password Reset Successfully</h1>
                <p>Your password has been reset to the default.</p>
                <br>
                <p>Please try to login, and if you have further issues, contact your instructor</p>
            </div>
        </div>
    </div>

{% endblock %}

apps/profiles/templates/profiles/instructor_signup.html
{% extends 'base.html' %}

{% block title %}Instructor Sign-Up{% endblock %}

{% block content %}
    <div class="ui vertical masthead center aligned segment">
        <div class="ui center aligned grid">
            <div class="ui six wide column message">

                <form class="ui form" method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    <div class="field">
                        {{ form.university_name.errors }}
                        {{ form.university_name.label_tag }}
                        {{ form.university_name }}
                    </div>

                    <input type="submit" value="Register as an Instructor">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

apps/profiles/templates/profiles/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="ui vertical masthead center aligned segment">
        <div class="ui center aligned grid">
            <div class="row">
                <div class="segment-container ui segment ten wide column">
                    <div class="ui header">
                        Login Here
                    </div>
                    <div class="container-content login-container ui twelve wide">
                        <form class="ui form" method="post">
                            {% csrf_token %}

                            {{ form.non_field_errors }}

                            <div class="field">
                                {{ form.email.errors }}
                                {{ form.email.label_tag }}
                                {{ form.email }}
                            </div>

                            <div class="field">
                                {{ form.password.errors }}
                                {{ form.password.label_tag }}
                                {{ form.password }}
                            </div>

                            <input class="ui button form-submit" type="submit" value="Login">
                            <input type="hidden" name="next" value="/"/>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="ui eight wide info column message">
                    <p>
                        Don't have an account? Create one <a href="{% url "profiles:sign_up" %}">here</a>!
                    </p>
                    <p>
                        Forgot your password? Request a reset: <a href="{% url "profiles:request_password_reset" sent_message=0 %}">here</a>!
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/profiles/templates/profiles/my_profile.html
{% extends 'base.html' %}

{% block title %}Your Profile{% endblock %}

{% block content %}
    <div class="ui vertical masthead center aligned segment">
        <div class="ui center aligned grid">
            <div class="ui twelve wide column message">
                <h1 class="ui dividing header">Your Profile</h1>
                <div style="margin-top: 5vh;" class="ui form">
                    <div class="field">
                        <span>
                            <b>Username:</b> {{ user.username }}
                        </span>
                    </div>
                    <div class="field">
                        <span>
                            <b>Email:</b> {{ user.email }}
                        </span>
                    </div>
                    <div class="field">
                        <span>
                            <b>First Name:</b> {{ user.first_name }}
                        </span>
                    </div>
                    <div class="field">
                        <span>
                            <b>Last Name:</b> {{ user.last_name }}
                        </span>
                    </div>
                </div>
                <div class="ui center aligned grid" style="margin-top: 5vh;" >
                    <div class="row">
                        <a href="{% url "profiles:change_password" %}" class="ui yellow icon button">
                            <i class="ui wrench icon"></i>
                            Change Password
                        </a>
                    </div>
                    <div class="row">
                        {% if not user.github_info %}
                            <a href="{% url "social:begin" "github" %}" class="ui green icon button">
                                <i class="ui github icon"></i>
                                Connect To GitHub
                            </a>
                        {% else %}
                            <div class="ui green icon disabled button">
                                <i class="ui github icon"></i>
                                Connected To GitHub
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/profiles/templates/profiles/password_reset_overview.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="ui header" style="">Password Reset Requests</h1>
    <div class="ui divider"></div>
    <table class="ui celled table">
        <thead>
        <tr>
            <th>User ID</th>
            <th>User Email</th>
            <th>User Display Name</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for request in password_reset_requests %}
            <tr>
                <td>{{ request.user.id }}</td>
                <td>{{ request.user.email }}</td>
                <td>{{ request.user.username }}</td>
                <td>
                    <form action="{% url "profiles:reset_user_password" user_pk=request.user.pk %}" method="post">
                        {% csrf_token %}
                        <input class="ui yellow icon button" type="submit" name="Reset Password"
                               value="Reset Password"/>
                    </form>
                </td>
                <td>
                    <form action="{% url "profiles:remove_user_password_reset_requests" user_pk=request.user.pk %}"
                          method="post">
                        {% csrf_token %}
                        <input class="ui red icon button" type="submit" name="Delete Request" value="Delete Request"/>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

apps/profiles/templates/profiles/request_password_reset.html
{% extends 'base.html' %}

{% block wizard_title %}
    <h2 class="ui massive header" style="font-size: 56px;">Request Password Reset</h2>
{% endblock %}

{% block content %}
    <div class="ui center aligned grid">

        <div class="fluid row">
            {% if sent_message %}
                <div class="ui success message">
                    <div class="header">
                        If the email supplied was correct, an email has been sent!
                    </div>
                </div>
            {% endif %}
        </div>

        <div class="six wide column">
            <div class="ui center aligned segment">
                <p>Please enter your email.</p>
                <p>You will receive an email with a link to reset your password.</p>
                <form class="ui form" action="" method="post">
                    {% csrf_token %}
                    <div class="sixteen wide field">
                        <label for="email">Email: </label>
                        <input id="email" type="text" name="email" value="">
                    </div>
                    <input class="ui yellow button" type="submit" value="Request Reset">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

apps/profiles/templates/profiles/set_password.html
{% extends 'base.html' %}

{% block title %}Change Your Password{% endblock %}

{% block content %}
    <div class="ui vertical masthead center aligned segment">

        {% if user.has_set_password %}
            <div class="ui red message">You have already set a password for this account. Please use 'Change Password' instead.</div>
        {% endif %}

        <div class="ui center aligned grid">
            <div class="ui six wide column message">

                <form class="ui form" method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    <div class="{% if user.has_set_password %}disabled {% endif %}field">
                        {{ form.new_password1.errors }}
                        {{ form.new_password1.label_tag }}
                        {{ form.new_password1 }}
                    </div>

                    <div class="{% if user.has_set_password %}disabled {% endif %}field">
                        {{ form.new_password2.errors }}
                        {{ form.new_password2.label_tag }}
                        {{ form.new_password2 }}
                    </div>


                    <input type="submit" {% if user.has_set_password %}disabled{% endif %} value="Change Password">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

apps/profiles/templates/profiles/sign_up.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="ui vertical masthead center aligned segment">
        <div class="ui center aligned grid">
            <div class="row">
                <div class="segment-container ui segment ten wide column">
                    <div class="ui header">
                        Create an Account
                    </div>
                    <div class="container-content login-container ui twelve wide">
                        <form class="ui form" method="post">
                            {% csrf_token %}

                            {{ form.non_field_errors }}

                            <div class="field">
                                {{ form.username.errors }}
                                {{ form.username.label_tag }}
                                {{ form.username }}
                            </div>

                            <div class="field">
                                {{ form.email.errors }}
                                {{ form.email.label_tag }}
                                {{ form.email }}
                            </div>

                            <div class="field">
                                {{ form.first_name.errors }}
                                {{ form.first_name.label_tag }}
                                {{ form.first_name }}
                            </div>

                            <div class="field">
                                {{ form.last_name.errors }}
                                {{ form.last_name.label_tag }}
                                {{ form.last_name }}
                            </div>

                            <div class="field">
                                {{ form.password1.errors }}
                                {{ form.password1.label_tag }}
                                {{ form.password1 }}
                            </div>

                            <div class="field">
                                {{ form.password2.errors }}
                                {{ form.password2.label_tag }}
                                {{ form.password2 }}
                            </div>

                            <input class="signup-btn ui button" type="submit" value="Sign-Up">
                            <input type="hidden" name="next" value="/"/>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                {#                <div class="ui eight wide yellow column message">#}
                {#                    <p>#}
                {#                        Don't have a Chahub account? Create on at <a href="chahub.org">Chahub.org</a> and then <a class="item" href="{% url "social:begin" "chahub" %}">Sign-In</a>#}
                {#                    </p>#}
                {#                </div>#}
            </div>
        </div>
    </div>
{% endblock %}