apps/api/urls.py
from django.conf.urls import url, include
from django.urls import path
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework.routers import SimpleRouter

from apps.api.views.homework import DefinitionViewSet, CriteriaViewSet, QuestionViewSet, SubmissionViewSet, \
    GradeViewSet, CustomChallengeURLViewSet
from apps.api.views.profiles import ProfileViewSet, StudentViewSet, create_students_from_csv, \
    TestStudentViewSet
from apps.api.views.klasses import KlassViewSet, HomeworkAnswersCSVView, EnrollStudentsSampleCSVView
from apps.api.views.groups import TeamViewSet
from apps.api.views import metrics


app_name = 'api'
API_PREFIX = "v1"

# API routes
router = SimpleRouter()
router.register('users', ProfileViewSet)
router.register('students', StudentViewSet)
router.register('test_students', TestStudentViewSet)
router.register('klasses', KlassViewSet)
router.register('definitions', DefinitionViewSet)
router.register('criterias', CriteriaViewSet)
router.register('questions', QuestionViewSet)
router.register('submissions', SubmissionViewSet)
router.register('grades', GradeViewSet)
router.register('teams', TeamViewSet)
router.register('custom_challenge_urls', CustomChallengeURLViewSet)

# Documentation details
schema_view = get_schema_view(
    openapi.Info(
        title="Chagrade API",
        default_version='v1',
        description="Chagrade is a platform for machine learning resources, like competitions, test sets, and example solutions",
        contact=openapi.Contact(email="info@codalab.org"),
        license=openapi.License(name="MIT License"),
    ),
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url('^', include(router.urls)),

    url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Docs
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=None), name='schema-json'),
    url(r'^$', schema_view.with_ui('swagger', cache_timeout=None), name='docs'),

    # Custom API point for handling student creation
    path('create_students_from_csv/', create_students_from_csv, name='create_students_from_csv'),

    # Enroll Students Upload Sample CSV
    path('enroll_students_sample_csv/', EnrollStudentsSampleCSVView.as_view(), name='enroll_students_sample_CSV'),

    # Metrics
    path('chagrade_overall_metrics/', metrics.chagrade_overall_metrics, name='chagrade_overall_metrics'),
    path('chagrade_student_metrics/', metrics.StudentMetricsView.as_view(), name='chagrade_student_metrics'),
    path('chagrade_instructor_metrics/', metrics.InstructorMetricsView.as_view(), name='chagrade_instructor_metrics'),
    path('chagrade_klass_metrics/', metrics.KlassMetricsView.as_view(), name='chagrade_klass_metrics'),
    path('chagrade_submission_metrics/', metrics.SubmissionMetricsView.as_view(), name='chagrade_submission_metrics'),
    path('student_submission_times/<int:student_pk>', metrics.StudentSubmissionTimesView.as_view(), name='student_submission_times'),
    path('student_scores/<int:student_pk>', metrics.StudentScoresView.as_view(), name='student_scores'),
    path('team_submission_times/<int:team_pk>', metrics.TeamSubmissionTimesView.as_view(), name='team_submission_times'),
    path('team_scores/<int:team_pk>', metrics.TeamScoresView.as_view(), name='team_scores'),
    path('team_contributions/<int:team_pk>', metrics.TeamContributionsView.as_view(), name='team_contributions'),
    path('klass_submission_times/<int:klass_pk>', metrics.KlassSubmissionTimesView.as_view(), name='klass_submission_times'),
    path('klass_scores/<int:klass_pk>', metrics.KlassScoresView.as_view(), name='klass_scores'),

    # CSV Metrics
    path('klass_csv/<int:klass_pk>', metrics.InstructorKlassCSVView.as_view(), name='klass_CSV'),
    path('student_csv/<int:student_pk>', metrics.InstructorStudentCSVView.as_view(), name='student_CSV'),
    path('team_csv/<int:team_pk>', metrics.InstructorTeamCSVView.as_view(), name='team_CSV'),

    path('klasses_csv/', metrics.AdminKlassCSVView.as_view(), name='klasses_CSV'),
    path('users_csv/', metrics.AdminUserCSVView.as_view(), name='users_CSV'),
    path('submissions_csv/', metrics.AdminSubmissionCSVView.as_view(), name='submissions_CSV'),

    # Homework answers CSV
    path('answers_csv/<int:klass_pk>/<int:definition_pk>/', HomeworkAnswersCSVView.as_view(), name='homework_answers_CSV'),
]

apps/homework/urls.py
from django.urls import path
from . import views


app_name = 'homework'

urlpatterns = [
    path('define/<int:klass_pk>/', views.DefinitionFormView.as_view(), name='define_homework'),
    path('edit_definition/<int:klass_pk>/<int:definition_pk>', views.DefinitionEditFormView.as_view(), name='edit_homework_def'),
    path('grade/<int:klass_pk>/submission/<int:submission_pk>/', views.GradeFormView.as_view(), name='grade_homework'),
    path('grade/<int:klass_pk>/submission/<int:submission_pk>/edit/<int:grade_pk>', views.GradeEditFormView.as_view(), name='edit_grade'),
    path('overview/<int:klass_pk>/', views.HomeworkOverView.as_view(), name='overview'),
    path('submissions/<int:definition_pk>/', views.SubmissionListView.as_view(), name='submission_list'),
    path('submission/<int:submission_pk>/', views.SubmissionDetailView.as_view(), name='submission_detail'),
    path('submit/<int:klass_pk>/<int:definition_pk>/<int:use_github>/', views.SubmissionFormView.as_view(), name='submit_homework'),
    path('edit_submission/<int:klass_pk>/<int:definition_pk>/<int:submission_pk>/<int:use_github>/', views.SubmissionEditFormView.as_view(), name='edit_submission'),
    path('download_grades_csv/<int:klass_pk>', views.get_klass_grades_as_csv, name='get_grades_csv'),
]

apps/klasses/urls.py
from django.urls import path

from apps.klasses import views

app_name = 'klasses'

urlpatterns = [
    path('create/', views.CreationView.as_view(), name='create_klass'),
    path('edit/<int:klass_pk>', views.EditView.as_view(), name='edit_klass'),
    path('wizard/<int:klass_pk>', views.OverView.as_view(), name='klass_details'),
    path('wizard/<int:klass_pk>/enroll', views.EnrollmentView.as_view(), name='klass_enrollment'),
    path('wizard/<int:klass_pk>/define_homework', views.DefineHomeworkView.as_view(), name='klass_homework'),
    path('wizard/<int:klass_pk>/grade_homework', views.GradeHomeworkView.as_view(), name='klass_grading'),
    path('wizard/<int:klass_pk>/answers/<int:definition_pk>/', views.HomeworkAnswersView.as_view(), name='homework_answers'),
    path('wizard/<int:klass_pk>/activate', views.ActivateView.as_view(), name='klass_activate'),
    path('download_student_csv/<int:klass_pk>', views.get_klass_students_as_csv, name='klass_get_student_csv'),
]

apps/metrics/urls.py
from django.urls import path

from apps.metrics import views

app_name = 'metrics'

urlpatterns = [
    path('klass/<int:klass_pk>', views.KlassMetricsView.as_view(), name='klass'),
    path('admin', views.AdminMetricsView.as_view(), name='admin'),
]

apps/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('reset_user_password/<int:user_pk>/', views.ResetUserPasswordView.as_view(), name='reset_user_password'),
    path('reset_password_by_email/<uuid:reset_key>/', views.ResetUserPasswordByEmailKeyView.as_view(), name='reset_password_by_email'),
    path('remove_user_password_reset_requests/<int:user_pk>/', views.DeletePasswordResetRequestsView.as_view(), name='remove_user_password_reset_requests'),
    path('request_password_reset/<int:sent_message>/', views.RequestResetView.as_view(), name='request_password_reset'),
    path('password_reset_requests/', views.PasswordRequestsOverView.as_view(), name='password_reset_requests'),
    path('instructor_signup/', views.InstructorProfileCreationView.as_view(), name='instructor_signup'),
    path('instructor_overview/', views.InstructorOverView.as_view(), name='instructor_overview'),
    path('student_overview/', views.StudentOverView.as_view(), name='student_overview'),
    path('my_profile/', views.MyProfileView.as_view(), name='my_profile')
]

chagrade/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView


from apps.klasses.models import Klass
from apps.homework.models import Submission
from apps.profiles.models import StudentMembership, ChaUser, Instructor

urlpatterns = [
    # Our includes
    path('admin/', admin.site.urls),
    path('profiles/', include('apps.profiles.urls', namespace='profiles')),
    path('klasses/', include('apps.klasses.urls', namespace='klasses')),
    path('metrics/', include('apps.metrics.urls', namespace='metrics')),
    path('homework/', include('apps.homework.urls', namespace='homework')),
    path('groups/', include('apps.groups.urls', namespace='groups')),
    path('social/', include('social_django.urls', namespace='social')),
    path('api/<str:version>/', include('apps.api.urls')),
]


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        stats_data = {
            "users": ChaUser.objects.count(),
            "students": StudentMembership.objects.count(),
            "instructors": Instructor.objects.count(),
            "submissions": Submission.objects.count(),
            "klasses": Klass.objects.count(),
        }
        context.update(stats_data)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Home-Page'
        return context


urlpatterns.append(path('', IndexView.as_view(), name='index'))


# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/klasses/models.py
from django.core.files.base import ContentFile
from django.db import models

# Require an account type to determine users vs students?
# Or should we abstract two seperate sub-models from this one?


# models.PROTECT says to forbid the deletion of the referenced object. To delete it we ahve to manually delete all
# references.
from django.utils import timezone

from apps.homework.models import Submission, Grade
from chagrade.storage import PublicStorage


def upload_image(instance, filename):
    file_split = filename.split('.')
    file_extension = file_split[len(file_split) - 1]
    path = f'images/{instance.pk}/{instance.course_number}/class_image.{file_extension}'
    return path


def upload_syllabus(instance, filename):
    file_split = filename.split('.')
    file_extension = file_split[len(file_split) - 1]
    path = f'syllabi/{instance.pk}/{instance.course_number}/class_syllabus.{file_extension}'
    return path


class Klass(models.Model):
    # COMPLETE = 'complete'
    # INCOMPLETE = 'incomplete'

    instructor = models.ForeignKey('profiles.Instructor', related_name='klasses', on_delete=models.CASCADE)

    title = models.CharField(max_length=60, null=False, blank=False, default="New Course")
    course_number = models.SlugField(max_length=60, null=False, blank=False)
    description = models.TextField(null=True, blank=True, default="")

    created = models.DateTimeField(editable=False, default=timezone.now, null=True, blank=True)
    modified = models.DateTimeField(default=timezone.now, null=True, blank=True)

    # Don't like this related name but we already used .klasses
    group = models.ForeignKey('groups.Group', related_name='klasses', null=True, blank=True, on_delete=models.SET_NULL)

    image = models.ImageField(null=True, blank=True, upload_to=upload_image, storage=PublicStorage())
    syllabus = models.FileField(null=True, blank=True, upload_to=upload_syllabus, storage=PublicStorage())

    active = models.BooleanField(default=False)

    def __str__(self):
        return "{0} by {1}".format(self.course_number, self.instructor.user.username)

    @property
    def status(self):
        return "NOT-IMPLEMENTED"

    def create_copy(self):
        new_klass = Klass()
        new_klass.instructor = self.instructor
        new_klass.title = self.title
        new_klass.description = self.description
        if self.image:
            print("we have an image")
            new_klass.image = ContentFile(self.image.read())
        if self.syllabus:
            print("We have a syllabus")
            new_klass.syllabus = ContentFile(self.syllabus.read())
        new_klass.group = self.group

        new_klass.course_number = self.course_number
        new_klass.save()
        return new_klass

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super().save(*args, **kwargs)

    def homeworks_completely_graded(self):
        for hw in self.homework_definitions.all():
            hw_graded = False
            if hw.team_based:
                for team in self.teams.all():
                    team_graded = False
                    submissions = Submission.objects.filter(team=team, definition=hw)
                    for submission in submissions:
                        if Grade.objects.filter(submission=submission, published=False):
                            return False
                        if Grade.objects.filter(submission=submission, published=True):
                            team_graded = True
                            break
                    if not submissions:
                        team_graded = True
                    if not team_graded:
                        return False
                hw_graded = True

            else:
                for student in self.enrolled_students.all():
                    student_graded = False
                    submissions = Submission.objects.filter(creator=student, definition=hw)
                    for submission in submissions:
                        if Grade.objects.filter(submission=submission, published=False):
                            return False
                        if Grade.objects.filter(submission=submission, published=True):
                            student_graded = True
                            break
                    if not submissions:
                        student_graded = True
                    if not student_graded:
                        return False
                hw_graded = True
            if not hw_graded:
                return False
        return True

apps/klasses/forms.py
from django import forms
from apps.klasses.models import Klass


class KlassForm(forms.ModelForm):
    class Meta:
        model = Klass
        fields = [
            'title',
            'course_number',
            'description',
            'image',
            'syllabus',
        ]

apps/metrics/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.views.generic import TemplateView
from django.http import Http404
from apps.klasses.models import Klass


class AdminMetricsView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'metrics/admin_metrics.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super(AdminMetricsView, self).get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Admin-Metrics'
        return context


class KlassMetricsView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'metrics/klass_metrics.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        klass_pk = self.kwargs.get('klass_pk')
        try:
            klass = Klass.objects.get(pk=klass_pk)
        except ObjectDoesNotExist:
            raise Http404('Klass object not found')
        if self.request.user.instructor:
            if self.request.user.instructor == klass.instructor:
                return True
        return False

    def get_context_data(self, **kwargs):
        context = super(KlassMetricsView, self).get_context_data(**kwargs)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Instructor-Metrics'
        klass_pk = self.kwargs['klass_pk']
        try:
            klass = Klass.objects.get(pk=klass_pk)
            context['klass'] = klass
        except ObjectDoesNotExist:
            raise Http404
        return context

apps/klasses/templates/klasses/wizard/activate_klass.html
{% extends 'klasses/wizard/wizard_base.html' %}

{% block extra_head %}
    <style>
        .wide-button {
            width: 50%
        }
    </style>
{% endblock %}

{% block wizard_title %}
    <h2 class="ui massive header" style="font-size: 56px;">Activate Class</h2>
{% endblock %}

{% block wizard_content %}
    <activate-klass student_homework_view_url="{% url "homework:overview" klass_pk=klass.pk %}"></activate-klass>
{% endblock %}

apps/klasses/templates/klasses/wizard/define_homework.html
{% extends 'klasses/wizard/wizard_base.html' %}

{% block wizard_title %}
    <h2 class="ui massive header" style="font-size: 56px;">Define Homework</h2>
{% endblock %}

{% block wizard_content %}
    <div class="ui fourteen wide column message">
        <div>
            <span>
                <a href="{% url "homework:define_homework" klass_pk=klass.pk %}" class="ui yellow button">Create Homework</a>
            </span>
            <h1>Homework</h1>
            <table class="ui sortable table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Creator</th>
                    <th>Last Modified</th>
                    <th>Due Date</th>
                    <th>Submissions</th>
                    <th></th>
                    <th>Entries</th>
                    <th>Avg. Grade</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for homework_def in klass.homework_definitions.all %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td>{{ homework_def.name }}</td>
                        <td>{{ homework_def.creator }}</td>
                        <td>{{ homework_def.updated_at }}</td>
                        <td>{{ homework_def.due_date }}</td>
                        <td>
                            <a class="ui mini blue button" href="{% url "homework:submission_list" definition_pk=homework_def.pk %}">Submissions</a>
                        </td>
                        <td>
                            <a class="ui mini yellow button" href="{% url "homework:edit_homework_def" klass_pk=klass.pk definition_pk=homework_def.pk %}">Edit</a>
                        </td>
                        <td>{{ homework_def.submissions.count }}</td>
                        <td>{{ homework_def.avg_grade }}</td>
                        <td><a id="{{ homework_def.pk }}" class="ui red mini button delete-definition">X</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
    <script>
        $(document).ready( function () {
            let delete_buttons = $('.delete-definition')
            delete_buttons.click( (e) => {
                let pk = $(e.target).attr('id')
                let affirmative = confirm('Are you sure you wish to delete this homework?')
                if (affirmative) {
                    delete_definition(pk)
                }
            })

            if (window.location.href.includes("deleted=true")){
                return toastr.success("Successfully deleted homework")
            }

            function delete_definition(pk) {
                CHAGRADE.api.delete_definition(pk)
                    .done(function (data) {
                        window.location = '/klasses/wizard/{{ klass.pk }}/define_homework?deleted=true'
                    })
                    .fail(function (response) {
                        Object.keys(response.responseJSON).forEach(function (key) {
                            toastr.error("Error with " + key + "! " + response.responseJSON[key])
                        });
                    })
            }
        })
    </script>
{% endblock %}

apps/klasses/templates/klasses/wizard/enroll.html
{% extends 'klasses/wizard/wizard_base.html' %}

{% block wizard_title %}
    <h2 class="ui massive header" style="font-size: 56px;">Enroll Students</h2>
{% endblock %}

{% block wizard_content %}
    <div class="ui fourteen wide column message">
        <participants-table></participants-table>
    </div>
{% endblock %}

apps/klasses/templates/klasses/wizard/overview.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <a class="ui blue button" href="{% url 'profiles:instructor_overview' %}">Back to Instructor Overview</a>
    <div class="fourteen wide column">

        {% include "klasses/klass_header.html" %}

        {% if object.active %}
            <a href="{% url "metrics:klass" klass_pk=object.pk %}" class="ui basic blue button">
                <i class="ui chart bar outline icon"></i>
                Metrics
            </a>
        {% else %}
            <div class="ui warning message">
                Class Status: NOT ACTIVE
            </div>
        {% endif %}

        <div class="ui vertical steps" style="width: 100%">
            <a href="{% url "klasses:klass_enrollment" klass_pk=klass.pk %}" class="{% if klass.enrolled_students.count > 0 %}completed {% endif %}step">
                <i class="users icon"></i>
                <div class="content">
                    <div class="title">Enroll Students</div>
                    <div class="description">Choose your shipping options</div>
                </div>
            </a>
            <a href="{% url "klasses:klass_homework" klass_pk=klass.pk %}" class="{% if klass.homework_definitions.count > 0 %}completed {% endif %}step">
                <i class="student icon"></i>
                <div class="content">
                    <div class="title">Define Homework</div>
                    <div class="description">Attach competitions to homework and define deadlines</div>
                </div>
            </a>
            <a href="{% url "klasses:klass_grading" klass_pk=klass.pk %}" class="{% if completely_graded %}completed {% endif %}step">
                <i class="pencil alternate icon"></i>
                <div class="content">
                    <div class="title">Grade Homework</div>
                    <div class="description">Make grades, publish them</div>
                </div>
            </a>
            <a href="{% url "klasses:klass_activate" klass_pk=klass.pk %}" class="{% if klass.active %}completed {% endif %}step">
                <i class="info icon"></i>
                <div class="content">
                    <div class="title">Activate Class</div>
                    <div class="description">Make class visible to students</div>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

apps/klasses/templates/klasses/wizard/wizard_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="ui centered grid">
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui centered grid">
                    <div class="row">
                        <div class="ui center aligned container" style="">
                            <h2 class="ui massive header" style="font-size: 56px;">
                                {% block wizard_title %}{% endblock %}</h2>
                            {% block wizard_description %}{% endblock %}
                        </div>
                    </div>
                    <div class="row">
                        <a href="{% url "klasses:klass_details" klass_pk=klass.pk %}" class="ui green button">Back to
                            Class Overview</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="sixteen wide center aligned column">
                <div class="ui mini steps">
                    <a href="{% url "klasses:klass_enrollment" klass_pk=klass.pk %}"
                       class="{% if klass.enrolled_students.count > 0 %}completed {% endif %}{% if wizard_current == 'klass_enrollment' %}active {% endif %}step">
                        <i class="users icon"></i>
                        <div class="content">
                            <div class="title">Enroll Students</div>
                        </div>
                    </a>
                    <a href="{% url "klasses:klass_homework" klass_pk=klass.pk %}"
                       class="{% if klass.homework_definitions.count > 0 %}completed {% endif %}{% if wizard_current == 'klass_homework' or wizard_current == 'define_homework' %}active {% endif %}step">
                        <i class="student icon"></i>
                        <div class="content">
                            <div class="title">Define Homework</div>
                        </div>
                    </a>
                    <a href="{% url "klasses:klass_grading" klass_pk=klass.pk %}"
                       class="{% if completely_graded %}completed {% endif %}{% if wizard_current == 'klass_grading' or wizard_current == 'grade_homework' %}active {% endif %}step">
                        <i class="pencil alternate icon"></i>
                        <div class="content">
                            <div class="title">Grade Homework</div>
                        </div>
                    </a>
                    <a href="{% url "klasses:klass_activate" klass_pk=klass.pk %}"
                       class="{% if klass.active %}completed {% endif %}{% if wizard_current == 'klass_activate' %}active {% endif %}step">
                        <i class="info icon"></i>
                        <div class="content">
                            <div class="title">Activate Class</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="sixteen wide column">
                <div class="ui blue inverted mini menu" style="margin-top: 5vh;">
                    {% if wizard_previous %}
                        <a href="{{ wizard_previous }}" class="item">
                            Previous
                        </a>
                    {% endif %}
                    {% if wizard_next %}
                        <div class="right menu">
                            <a href="{{ wizard_next }}" class="item">
                                Next
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="sixteen wide column">
                {% block wizard_content %}
                {% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="sixteen wide column">
                <div class="ui blue inverted mini menu" style="margin-top: 5vh;">
                    {% if wizard_previous %}
                        <a href="{{ wizard_previous }}" class="item">
                            Previous
                        </a>
                    {% endif %}
                    {% if wizard_next %}
                        <div class="right menu">
                            <a href="{{ wizard_next }}" class="item">
                                Next
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}