apps/metrics/urls.py
from django.urls import path

from apps.metrics import views

app_name = 'metrics'

urlpatterns = [
    path('klass/<int:klass_pk>', views.KlassMetricsView.as_view(), name='klass'),
    path('admin', views.AdminMetricsView.as_view(), name='admin'),
]

apps/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('reset_user_password/<int:user_pk>/', views.ResetUserPasswordView.as_view(), name='reset_user_password'),
    path('reset_password_by_email/<uuid:reset_key>/', views.ResetUserPasswordByEmailKeyView.as_view(), name='reset_password_by_email'),
    path('remove_user_password_reset_requests/<int:user_pk>/', views.DeletePasswordResetRequestsView.as_view(), name='remove_user_password_reset_requests'),
    path('request_password_reset/<int:sent_message>/', views.RequestResetView.as_view(), name='request_password_reset'),
    path('password_reset_requests/', views.PasswordRequestsOverView.as_view(), name='password_reset_requests'),
    path('instructor_signup/', views.InstructorProfileCreationView.as_view(), name='instructor_signup'),
    path('instructor_overview/', views.InstructorOverView.as_view(), name='instructor_overview'),
    path('student_overview/', views.StudentOverView.as_view(), name='student_overview'),
    path('my_profile/', views.MyProfileView.as_view(), name='my_profile')
]

chagrade/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView


from apps.klasses.models import Klass
from apps.homework.models import Submission
from apps.profiles.models import StudentMembership, ChaUser, Instructor

urlpatterns = [
    # Our includes
    path('admin/', admin.site.urls),
    path('profiles/', include('apps.profiles.urls', namespace='profiles')),
    path('klasses/', include('apps.klasses.urls', namespace='klasses')),
    path('metrics/', include('apps.metrics.urls', namespace='metrics')),
    path('homework/', include('apps.homework.urls', namespace='homework')),
    path('groups/', include('apps.groups.urls', namespace='groups')),
    path('social/', include('social_django.urls', namespace='social')),
    path('api/<str:version>/', include('apps.api.urls')),
]


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        stats_data = {
            "users": ChaUser.objects.count(),
            "students": StudentMembership.objects.count(),
            "instructors": Instructor.objects.count(),
            "submissions": Submission.objects.count(),
            "klasses": Klass.objects.count(),
        }
        context.update(stats_data)
        context['wiki_page_url'] = 'https://github.com/codalab/chagrade/wiki/Home-Page'
        return context


urlpatterns.append(path('', IndexView.as_view(), name='index'))


# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load admin_urls %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}{% endblock %}</title>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.0/dist/semantic.min.css">

    <script src="//cdn.jsdelivr.net/npm/semantic-ui@2.4.0/dist/semantic.min.js"></script>

    <script src="//semantic-ui.com/javascript/library/tablesort.js"></script>

    <script src="//cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.14/lodash.min.js"></script>

    <!-- Riot -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/riot/3.11.2/riot+compiler.min.js"></script>

    <script src="{% static "js/jquery.form.serializer.js" %}"></script>

    <script src="{% static "js/ours/client.js" %}"></script>

    <link rel="shortcut icon" href="{% static 'images/chagrade_C.png' %}">

    <link rel="stylesheet" href="//use.fontawesome.com/26ae41ff0f.css">
    <link href="//fonts.googleapis.com/css?family=Cabin|Raleway" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    <link rel="stylesheet" href="{% static "css/calendar.min.css" %}">
    <script src="{% static "js/calendar.min.js" %}"></script>
    <script src="{% static "js/luxon.js" %}"></script>

    <!-- Our Riot -->
    <script src="{% static "riotjs/wizard/participants_table.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/teams_table.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/criteria_table.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/question_table.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/activate_klass.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/define_extra_questions.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/define_criteria.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/student/submit_homework.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/student/submission_detail_github.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/student/submission_diff.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/student/accordion_file_tree.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/grade_homework.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/define_homework.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/wizard/create_team.tag" %}" type="riot/tag"></script>
    <script src="{% static "riotjs/show_stats.tag" %}" type="riot/tag"></script>

    {% block extra_head %}
    {% endblock %}

</head>

<body class="main-background">
<div id="particles-js"></div>

<header class="center aligned header-container">
    <div id="logo">
        <div class="button-suite">
            <a class="ui icon button" href="{{ wiki_page_url }}" id="wiki-page-button"
               target="_blank" rel="noopener noreferrer"
               data-content="Wiki for this page.">
                <i class="question mark icon"></i>
            </a>
            {% if user.is_authenticated %}
                <span class="ui login-button dropdown button item">
                    <span class="text">
                        <i class="icon user outline"></i>
                        {{ user.username }}
                    </span>
                    <i class="dropdown icon"></i>
                    <span class="menu">
                    {% if user.is_staff or user.is_superuser %}
                        <div class="header">Django Admin</div>
                        <a class="item" href="{% url 'admin:index' %}">Index</a>
                        <a class="item" href="{% url 'admin:index' %}homework/">Homework</a>
                        <a class="item" href="{% url 'admin:index' %}klasses/">Classes</a>
                        <a class="item" href="{% url 'admin:index' %}profiles/">Profiles</a>
                        <a class="item" href="{% url 'metrics:admin' %}">Metrics</a>
                    {% endif %}
                        <div class="ui divider"></div>
                        <div class="header">Chasuite</div>
                            <a class="item" href="https://competitions.codalab.org/">Codalab</a>
                            <a class="item" href="https://chahub.org/">Chahub</a>
                            <a class="item" href="https://chalab.lri.fr/">Chalab</a>
                        <div class="ui divider"></div>
                        <div class="header">My Account</div>
                        <a class="item" href="/profiles/my_profile">
                            <i class="icon user"></i>
                            My profile
                        </a>
                        <a class="item" href="{% url "profiles:logout" %}">
                            <i class="icon sign out"></i>
                            Logout
                        </a>
                    </span>
                </span>
                {% if user.is_staff or user.is_superuser %}
                    {% if password_reset_requests %}
                        <a class="item" href="{% url "profiles:password_reset_requests" %}">
                            Password Reset Requests
                            {% if password_reset_requests.count > 0 %}
                                <div class="floating ui red label">{{ password_reset_requests.count }}</div>{% endif %}
                        </a>
                    {% endif %}
                {% endif %}
            {% else %}
                <a class="ui button" href="{% url "profiles:login" %}">Login</a>
            {% endif %}
        </div>
        <a id="home-logo" class="logo" href="/"></a>
    </div>

</header>
<div class="ui container">
    <div class="app">
        <div class="ui segment hide-border">
            <div class="module container-padding">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <footer class="ui footer">
        <div class="ui horizontal link list">
            <a class="item" href="https://github.com/codalab/chagrade/issues"
               target="_blank" rel="noopener noreferrer">
                <i class="github icon"></i>
                Join us on Github for contact & Bug Reports.
            </a>
            <a class="item">
                Work In Progress - Version 0.1
            </a>
        </div>
    </footer>
</div>

<script>

    // Load in URLs or other django generated goodies
    var URLS = {
        API: "/api/v1/"
    }
    var USER_AUTHENTICATED = ("{{ user.is_authenticated }}" === "True")
    {% if klass %}
        var KLASS = {{ klass.pk }}
    {% endif %}
    {% if definition %}
        var DEFINITION = {{ definition.pk }}
    {% endif %}
    {% if user.is_authenticated and user.instructor %}
        var INSTRUCTOR = {{ user.instructor.pk }}
    {% endif %}
    {% if submission %}
        var SUBMISSION = {{ submission.pk }}
    {% endif %}
    {% if student %}
        var STUDENT = {{ student.pk }}
    {% endif %}
    {% if grade %}
        var GRADE = {{ grade.pk }}
    {% endif %}
    {% if student and definition and definition.team_based and student.team %}
        console.log("Definition is team based")
        var USER_TEAM = {{ student.team.pk }}
    {% endif %}
    {# This one is passed as a PK like the rest should probably be #}
    {% if team %}
        var TEAM = {{ team.pk }}
    {% endif %}

    {% block extra_js_context %}
    {% endblock %}

    $('document').ready(function () {
        $('table').tablesort();
        $('.dropdown.login-button').dropdown();

        particlesJS.load('particles-js', "{% static 'particles/particles.json' %}", function () {
            console.log('callback - particles.js config loaded');
        })

        $('#wiki-page-button').popup()
    });

    riot.mount('*')
</script>

{% block extra_script %}
{% endblock %}

<style>
    #home-logo {
        background-image: url('{% static "images/chagrade_logo.png" %}');
        background-size: contain;
        background-repeat: no-repeat;
        height: 40px;
        width: 220px;
    }
</style>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="ui centered grid">
            <div class="row">
{#                <div class="six wide column">#}
{#                    <div class="segment-container ui segment sixteen wide">#}
{#                        <div class="ui header">#}
{#                            Announcements#}
{#                        </div>#}
{#                        <div class="container-content">#}
{#                            <div class="recent-activity sixteen wide column">#}
{#                                <div class="">#}
{#                                    <div class="list-tile">#}
{#                                        <a href="#">Competition: Finding relevant data on ice floes</a>#}
{#                                        <div class="date-complete">Homework Due: 03/01/2018</div>#}
{#                                    </div>#}
{#                                    <div class="list-tile">#}
{#                                        <a href="#">Submission: Pathfinding in the dark</a>#}
{#                                        <div class="date-complete">Homework Due: 03/01/2018</div>#}
{#                                    </div>#}
{#                                    <div class="list-tile">#}
{#                                        <a href="#">Dataset: Handwriting</a>#}
{#                                        <div class="date-complete">Homework Due: 03/01/2018</div>#}
{#                                    </div>#}
{#                                    <div class="list-tile">#}
{#                                        <a href="#">Submission: Pathfinding in the dark</a>#}
{#                                        <div class="date-complete">Homework Due: 03/01/2018</div>#}
{#                                    </div>#}
{#                                    <div class="list-tile">#}
{#                                        <a href="#">Dataset: Handwriting</a>#}
{#                                        <div class="date-complete">Homework Due: 03/01/2018</div>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
                <div class="twelve wide column">
                    <div class="segment-container ui segment column">
                        <div class="ui header">
                            Students and Instructors
                        </div>
                        <div class="eight wide column container-content">
                            <div class="sixteen wide column">
                                <div class="ui row">
                                    <p class="student-instructor">
                                        The Student and Instructor portals will allow you to assign and turn in
                                        homework. Anyone can create and complete assignments! Instructors can easily
                                        create homework with the homework wizard in the Instructor View and students can
                                        turn in homework in the Student View.
                                    </p>
                                </div>
                                <div class="ui row student-instructor-flex ">
                                    <div class="eight wide column">
                                        <a class="ui large button view-btn" href="{% url "profiles:student_overview" %}"
                                           role="button">Student View</a>
                                    </div>
                                    <div class="eight wide column">
                                        <a class="ui large button view-btn" href="{% url "profiles:instructor_overview" %}"
                                           role="button">Instructor View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="four wide column">
                    <div class="segment-container ui segment sixteen wide">
                        <div class="ui header">
                            By the numbers...
                        </div>
                        <div class="container-content">
                            <show-stats students="{{ students }}" instructors="{{ instructors }}" klasses="{{ klasses }}" users="{{ users }}" submissions="{{ submissions }}" ></show-stats>
                        </div>
                    </div>
                </div>
            </div>

            <div id="about-container" class="segment-container ui segment sixteen wide">
                <div class="ui header">
                    About Chagrade
                </div>
                <div class="container-content ui grid three column">
                    <div class="center aligned column">
                        <h3 class="ui icon header">
                            <i class="student icon"></i>
                            Learning By Doing
                        </h3>
                        <div>
                            <p>Challenges make great projects. Students learn by solving actual machine learning
                                problems.
                                They can submit code, which is automatically evaluated by the challenge
                                platform.</p>
                        </div>
                    </div>
                    <div class="center aligned column">
                        <h3 class="ui icon header">
                            <i class="users icon"></i>
                            Collaborating
                        </h3>
                        <div>
                            <p>Students can work individually or in teams. A class can mix individual and team
                                homework.
                                Homework can include questions on top of challenge performance.</p>
                        </div>
                    </div>
                    <div class="center aligned column">
                        <h3 class="ui icon header">
                            <i style="font-size: 3em;" class="square github icon"></i>
                            Gaining Visibility
                        </h3>
                        <div>
                            <p>Teachers can provide a starting kit in a github repo that students can clone and
                                modify. They can start building a portfolio with these projects using Github.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    {% else %}

        <div class="ui centered grid">
            <div class="row">
                <div class="twelve wide column">
                    <div class="ui centered grid message">
                        <div class="row">
                            <div class="ui center aligned container" style="margin-bottom: 5px;">
                                <h1 class="ui massive header" style="font-size: 56px;">Welcome to Chagrade</h1>
                                <h2 class="sub header">
                                    Here you can create <b>and grade classes attached to challenges</b>
                                </h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="center aligned twelve wide column">
                                <a class="ui large button signup-btn" href="{% url "profiles:sign_up" %}" role="button">Sign
                                    Up</a>
                                <a class="ui large button login-btn" href="{% url "profiles:login" %}"
                                   role="button">Login</a>
                            </div>
                            {#                            <div class="center aligned six wide column">#}
                            {#                                <a class="ui large blue button" href="{% url "profiles:login" %}" role="button">Login</a>#}
                            {#                            </div>#}
                        </div>
                    </div>
                </div>
                <div class="four wide column">
                    <div class="segment-container ui segment sixteen wide">
                        <div class="ui header">
                            By the numbers...
                        </div>
                        <div class="container-content">
                            <show-stats students="{{ students }}" instructors="{{ instructors }}" klasses="{{ klasses }}" users="{{ users }}" submissions="{{ submissions }}" ></show-stats>
                        </div>
                    </div>
                </div>
            </div>
            {#            <div class="ui three column row">#}
            {#                <div class="center aligned column">#}
            {#                    <h3 class="ui icon header">#}
            {#                        <i class="student icon"></i>#}
            {#                        <div class="content">#}
            {#                            Learning By Doing#}
            {#                        </div>#}
            {#                    </h3>#}
            {#                    <div style="">#}
            {#                        <p>As a student, manage enrolled classes, make Homework Submissions, and view grades.</p>#}
            {#                    </div>#}
            {#                </div>#}
            {#                <div class="center aligned column">#}
            {#                    <h3 class="ui icon header">#}
            {#                        <i class="users icon"></i>#}
            {#                        <div class="content">#}
            {#                            Learning By Doing#}
            {#                        </div>#}
            {#                    </h3>#}
            {#                    <div style="">#}
            {#                        <p>As a student, manage enrolled classes, make Homework Submissions, and view grades.</p>#}
            {#                    </div>#}
            {#                </div>#}
            {#                <div class="center aligned column">#}
            {#                    <h3 class="ui icon header">#}
            {#                        <i class="square github icon"></i>#}
            {#                        <div class="content">#}
            {#                            Learning By Doing#}
            {#                        </div>#}
            {#                    </h3>#}
            {#                    <div style="">#}
            {#                        <p>As a student, manage enrolled classes, make Homework Submissions, and view grades.</p>#}
            {#                    </div>#}
            {#                </div>#}
            {#            </div>#}
            <div id="about-container" class="segment-container ui segment sixteen wide">
                <div class="ui header">
                    About Chagrade
                </div>
                <div class="container-content ui grid three column">
                    <div class="center aligned column">
                        <h3 class="ui icon header">
                            <i class="student icon"></i>
                            Learning By Doing
                        </h3>
                        <div>
                            <p>Challenges make great projects. Students learn by solving actual machine learning
                                problems.
                                They can submit code, which is automatically evaluated by the challenge
                                platform.</p>
                        </div>
                    </div>
                    <div class="center aligned column">
                        <h3 class="ui icon header">
                            <i class="users icon"></i>
                            Collaborating
                        </h3>
                        <div>
                            <p>Students can work individually or in teams. A class can mix individual and team
                                homework.
                                Homework can include questions on top of challenge performance.</p>
                        </div>
                    </div>
                    <div class="center aligned column">
                        <h3 class="ui icon header">
                            <i style="font-size: 3em;" class="square github icon"></i>
                            Gaining Visibility
                        </h3>
                        <div>
                            <p>Teachers can provide a starting kit in a github repo that students can clone and
                                modify. They can start building a portfolio with these projects using Github.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}

{% endblock %}

templates/instructor_index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

    <div class="ui inverticed vertical masthead center aligned segment">
        <h1 class="ui massive header">Welcome to Chagrade</h1>
        <h6 class="ui sub header">
            Here you can enroll in classes as a student or instruct and manage them as an instructor.
        </h6>
        <a class="ui large green button" href="" role="button">Sign Up</a>
    </div>
    <div class="ui grid">
        <div class="three column row">
            <div class="center aligned column">
                <h1><i class="large cloud upload icon"></i>Upload:</h1>
                Upload your data and baseline methods. The platform lets you choose among pre-loaded
                datasets or lets you upload your own in a simple text-based format. The platform
                also lets you upload a starting kit to help the participants solve there tasks.
                A Python example is provided.
            </div>
            <div class="center aligned column">
                <h1><i class="large wrench icon"></i>Design:</h1>
                Prepare your very own challenge protocol and rules. The platform helps you create
                tasks by automatically splitting your data and letting you choose among pre-defined
                metrics. An editor helps you add documentation pages.
            </div>
            <div class="center aligned column">
                <h1><i class="large ship icon"></i>Ship:</h1>
                The platform compiles your tasks, sample code, and documentation into a
                self-contained zip archive, ready to upload to a competition platform.
                (in this version, Codalab.org is supported).
            </div>index.html
        </div>
    </div>

{% endblock %}

templates/student_index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

{#    <div class="ui inverticed vertical masthead center aligned segment">#}
{#        <h1 class="ui massive header">Welcome to Chagrade</h1>#}
{#        <h6 class="ui sub header">#}
{#            Here you can enroll in classes as a student or instruct and manage them as an instructor.#}
{#        </h6>#}
{#        <a class="ui large green button" href="" role="button">Sign Up</a>#}
{#    </div>#}
{#    <div class="ui grid">#}
{#        <div class="three column row">#}
{#            <div class="center aligned column">#}
{#                <h1><i class="large cloud upload icon"></i>Upload:</h1>#}
{#                Upload your data and baseline methods. The platform lets you choose among pre-loaded#}
{#                datasets or lets you upload your own in a simple text-based format. The platform#}
{#                also lets you upload a starting kit to help the participants solve there tasks.#}
{#                A Python example is provided.#}
{#            </div>#}
{#            <div class="center aligned column">#}
{#                <h1><i class="large wrench icon"></i>Design:</h1>#}
{#                Prepare your very own challenge protocol and rules. The platform helps you create#}
{#                tasks by automatically splitting your data and letting you choose among pre-defined#}
{#                metrics. An editor helps you add documentation pages.#}
{#            </div>#}
{#            <div class="center aligned column">#}
{#                <h1><i class="large ship icon"></i>Ship:</h1>#}
{#                The platform compiles your tasks, sample code, and documentation into a#}
{#                self-contained zip archive, ready to upload to a competition platform.#}
{#                (in this version, Codalab.org is supported).#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

{% endblock %}

templates/student_mgmt.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

{#    <div class="ui inverticed vertical masthead center aligned segment">#}
{#        <h1 class="ui massive header">Welcome to Chagrade</h1>#}
{#        <h6 class="ui sub header">#}
{#            Here you can enroll in classes as a student or instruct and manage them as an instructor.#}
{#        </h6>#}
{#        <a class="ui large green button" href="" role="button">Sign Up</a>#}
{#    </div>#}
{#    <div class="ui grid">#}
{#        <div class="three column row">#}
{#            <div class="center aligned column">#}
{#                <h1><i class="large cloud upload icon"></i>Upload:</h1>#}
{#                Upload your data and baseline methods. The platform lets you choose among pre-loaded#}
{#                datasets or lets you upload your own in a simple text-based format. The platform#}
{#                also lets you upload a starting kit to help the participants solve there tasks.#}
{#                A Python example is provided.#}
{#            </div>#}
{#            <div class="center aligned column">#}
{#                <h1><i class="large wrench icon"></i>Design:</h1>#}
{#                Prepare your very own challenge protocol and rules. The platform helps you create#}
{#                tasks by automatically splitting your data and letting you choose among pre-defined#}
{#                metrics. An editor helps you add documentation pages.#}
{#            </div>#}
{#            <div class="center aligned column">#}
{#                <h1><i class="large ship icon"></i>Ship:</h1>#}
{#                The platform compiles your tasks, sample code, and documentation into a#}
{#                self-contained zip archive, ready to upload to a competition platform.#}
{#                (in this version, Codalab.org is supported).#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

{% endblock %}